os: linux
dist: xenial
language: node_js
node_js: lts/*
addons:
  ssh_known_hosts: tygr.info

# SSH Setup
before_deploy:
  - openssl aes-256-cbc
    -K $encrypted_db2095f63ba3_key
    -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc
    -out /tmp/deploy_rsa
    -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

script:
  - npm run quality:check
  - NODE_ENV=production npm run build

deploy:
  - on:
      branch: main
      tags: true
      repo: tylergrinn/tygr-header
    provider: npm
    email: tylergrinn@gmail.com
    skip_cleanup: true
    api_token:
      secure: Bbdl5K/5zS4MPAJ9d9vHWfthH5ET3jhhq5uE91+R90SdmxMawRgVUXEO9p2b+XxX6k7FRO4NtVJvzRtyLC+/H9YRgFg9G5C9L1tPXvcKbxfcJcfj9dKyBeVQw/qHEpJ2aFfCiMcM7mLnTCYcxu+j8+g32ARkd4mcvkhDrsouFtAC3OJykFRN6Nzs3ts6JdyJpWWpRQoNanxq7YHety62XFuqvXKLzpB4G1v3oPr947s+Q4d/r8vN5i92oBpcFyAoHxufXoNJCukqrI4olS3bluQlTOLE8B8yuJlcwEOyZEWgCZXnn+AN/fJ2PxR0jDuzywis/4hbgoAiDCqrYjpsqI/4tzSYhgrDC/UiiftEhr06seazl2TIQsAdFeP4DqwDjJ8JgVBQAhmoYthGZB6FbLjyZ/JsLZsBpYVyx62WB/svn9qLZCmj+dvi5hmmiTTD+PNbrh4JxPFMDZ6TnxAdMbDYGt8KxEuvK9aLogw5C4UiBB4PbSV+Bmg3VCO3a2g5OnisTwCaiKSEpHEvNbM6aCcJHLPLe4wqkFMMP6EGoY+K4EPaL9im6gxks170xQPzGKFtRBC5jHdvzahXndWiUbDRafkUDSRjlWu1wkRURGtVUHKnd7npi0jEA2V2FVmKXV4DIWvCjY11rDxcbcEOXYXcbwqWt67SceYhMcqRU+A=
  - on:
      branch: main
      tags: true
      repo: tylergrinn/tygr-header
    provider: script
    skip_cleanup: true
    script: rsync --recursive --delete lib node@tygr.info:@tygr/header
